// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvCHyS3vJWOZIJ__5OOsaJi2JEBd9ZFN4',
    appId: '1:515333812791:web:86ccd2d321aed26a35c5b2',
    messagingSenderId: '515333812791',
    projectId: 'alertnuke-ver2',
    authDomain: 'alertnuke-ver2.firebaseapp.com',
    storageBucket: 'alertnuke-ver2.appspot.com',
    measurementId: 'G-PWBJ3F7WXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1wuq8SBlMwDFY2xpZUqMQKU7HjRvUMkQ',
    appId: '1:515333812791:android:453f9899378aa88735c5b2',
    messagingSenderId: '515333812791',
    projectId: 'alertnuke-ver2',
    storageBucket: 'alertnuke-ver2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYQ0Rt2ck9Vx4htzyhIyCMGD2kH5zE1bw',
    appId: '1:515333812791:ios:3706714aa530805035c5b2',
    messagingSenderId: '515333812791',
    projectId: 'alertnuke-ver2',
    storageBucket: 'alertnuke-ver2.appspot.com',
    iosBundleId: 'com.example.alertukeVer2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYQ0Rt2ck9Vx4htzyhIyCMGD2kH5zE1bw',
    appId: '1:515333812791:ios:764babeae227d40a35c5b2',
    messagingSenderId: '515333812791',
    projectId: 'alertnuke-ver2',
    storageBucket: 'alertnuke-ver2.appspot.com',
    iosBundleId: 'com.example.alertukeVer2.RunnerTests',
  );
}
